import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const envPath = path.join(rootDir, '.env');
const envExamplePath = path.join(rootDir, '.env.example');

// If .env doesn't exist yet, bootstrap it from .env.example
if (!fs.existsSync(envPath) && fs.existsSync(envExamplePath)) {
  fs.copyFileSync(envExamplePath, envPath);
  console.log('[set-env] Created .env from .env.example');
}

const result = dotenv.config({ path: envPath });
if (result.error) {
  console.warn('[set-env] Warning: Could not parse .env file:', result.error.message);
}

const isProduction = process.env.NODE_ENV === 'production' || process.env.APP_ENV === 'production';
const apiUrl = process.env.API_URL || '/api';
const supabaseUrl = process.env.SUPABASE_URL || 'https://jtszesnaluflmaldqwme.supabase.co';
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY || '';
const authorEmail = process.env.AUTHOR_EMAIL || 'de.james013@gmail.com';
const useMockFallback = process.env.USE_MOCK_FALLBACK === 'true';

// Validation
const errors = [];
if (!supabaseUrl) errors.push('SUPABASE_URL is missing in .env');
if (!authorEmail) errors.push('AUTHOR_EMAIL is missing in .env');

if (errors.length > 0) {
  console.warn('[set-env] Configuration warnings:\n - ' + errors.join('\n - '));
}

const generatedConfigContent = `// Auto-generated by scripts/set-env.mjs from .env
// This file is gitignored and NOT committed to version control.

import { AppConfig } from './app-config';

export const generatedAppConfig: AppConfig = {
  production: ${isProduction},
  apiUrl: ${JSON.stringify(apiUrl)},
  supabaseUrl: ${JSON.stringify(supabaseUrl)},
  supabaseAnonKey: ${JSON.stringify(supabaseAnonKey)},
  authorEmail: ${JSON.stringify(authorEmail)},
  useMockFallback: ${useMockFallback},
};
`;

const configDir = path.join(rootDir, 'src', 'app', 'core', 'config');
if (!fs.existsSync(configDir)) {
  fs.mkdirSync(configDir, { recursive: true });
}

fs.writeFileSync(path.join(configDir, 'app-config.generated.ts'), generatedConfigContent, 'utf-8');

// Completely remove legacy dummy src/environments directory if present
const legacyEnvironmentsDir = path.join(rootDir, 'src', 'environments');
if (fs.existsSync(legacyEnvironmentsDir)) {
  fs.rmSync(legacyEnvironmentsDir, { recursive: true, force: true });
  console.log('[set-env] Cleaned up and removed legacy src/environments directory.');
}

console.log(`[set-env] App config compiled -> src/app/core/config/app-config.generated.ts (${isProduction ? 'PROD' : 'DEV'})`);
console.log(`[set-env] API_URL: ${apiUrl}`);
console.log(`[set-env] SUPABASE_URL: ${supabaseUrl}`);
console.log(`[set-env] AUTHOR_EMAIL: ${authorEmail}`);
console.log(`[set-env] SUPABASE_ANON_KEY: ${supabaseAnonKey ? `${supabaseAnonKey.slice(0, 10)}...${supabaseAnonKey.slice(-6)}` : '(NOT SET)'}`);
