// Auto-generated by scripts/set-env.mjs from .env
// This file is gitignored and NOT committed to version control.

import { AppConfig } from './app-config';

export const generatedAppConfig: AppConfig = {
  production: false,
  apiUrl: "/api",
  supabaseUrl: "https://jtszesnaluflmaldqwme.supabase.co",
  supabaseAnonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0c3plc25hbHVmbG1hbGRxd21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkyMTIyMzcsImV4cCI6MjEwNDc4ODIzN30.-BVPvHkTUoOXUQiBtqd1ktI-hy9C7koK0aeuqS4Wc-Q",
  authorEmail: "de.james013@gmail.com",
  useMockFallback: true,
};
